import ActivityKit
import AppIntents
import SwiftUI
import WidgetKit

struct ZmanEntry:TimelineEntry{let date:Date;let snapshot:ZmanSnapshot?;var next:ZmanItem?{snapshot?.items.first(where:{$0.date>date})}}
struct ZmanProvider:TimelineProvider{func placeholder(in context:Context)->ZmanEntry{.init(date:.now,snapshot:nil)};func getSnapshot(in context:Context,completion:@escaping(ZmanEntry)->Void){completion(.init(date:.now,snapshot:AppGroupStore.loadSnapshot()))};func getTimeline(in context:Context,completion:@escaping(Timeline<ZmanEntry>)->Void){let now=Date();completion(.init(entries:[.init(date:now,snapshot:AppGroupStore.loadSnapshot())],policy:.after(now.addingTimeInterval(300))))}}

struct ZmanimWidget:Widget{let kind="ZmanimWidget";var body:some WidgetConfiguration{StaticConfiguration(kind:kind,provider:ZmanProvider()){entry in ZmanWidgetView(entry:entry).containerBackground(.fill.tertiary,for:.widget)}.configurationDisplayName("זמני היום").description("הזמן הבא ומסלול השמש.").supportedFamilies([.systemSmall,.systemMedium,.systemLarge,.systemExtraLarge,.accessoryInline,.accessoryCircular,.accessoryRectangular])}}

struct ZmanWidgetView:View{@Environment(\.widgetFamily) private var family;let entry:ZmanEntry
 var body:some View{switch family{case .accessoryInline:Text(inlineText);case .accessoryCircular:Gauge(value:progress){Image(systemName:"sun.max.fill")}.gaugeStyle(.accessoryCircularCapacity);case .accessoryRectangular:VStack(alignment:.leading){Text(entry.next?.hebrewTitle ?? "זמנים").bold();Text(nextTime).monospacedDigit();Text(entry.next?.date ?? entry.date,style:.relative).font(.caption2)};case .systemSmall:small;case .systemMedium:medium;default:large}}
 private var small:some View{VStack(alignment:.leading,spacing:8){Label(entry.snapshot?.cityName ?? "זמנים",systemImage:"location.fill").font(.caption).foregroundStyle(.secondary);Spacer();Image(systemName:entry.next?.icon ?? "sun.max.fill").font(.title2).foregroundStyle(.orange);Text(entry.next?.hebrewTitle ?? "טוען…").font(.headline);Text(nextTime).font(.title.monospacedDigit().bold());Button(intent:ToggleQuickReminderIntent()){Label(AppGroupStore.quickReminderEnabled ? "תזכורת פעילה":"הזכר לי",systemImage:AppGroupStore.quickReminderEnabled ? "bell.fill":"bell")}.font(.caption)}}
 private var medium:some View{HStack{VStack(alignment:.leading,spacing:6){Text("הזמן הבא").font(.caption).foregroundStyle(.secondary);Text(entry.next?.hebrewTitle ?? "טוען…").font(.title3.bold());Text(nextTime).font(.title.monospacedDigit().bold());Text(entry.next?.date ?? entry.date,style:.relative).font(.caption).foregroundStyle(.orange)};Spacer();SolarMini(snapshot:entry.snapshot,now:entry.date).frame(width:150,height:90)}}
 private var large:some View{VStack(alignment:.leading,spacing:12){HStack{Text("זמני היום").font(.title2.bold());Spacer();Text(entry.snapshot?.cityName ?? "").foregroundStyle(.secondary)};SolarMini(snapshot:entry.snapshot,now:entry.date).frame(height:110);ForEach(Array((entry.snapshot?.items.filter{$0.date>entry.date}.prefix(5) ?? []).enumerated()),id:\.element.id){_,item in HStack{Image(systemName:item.icon).frame(width:25);Text(item.hebrewTitle);Spacer();Text(time(item.date)).monospacedDigit()}};Spacer()}}
 private var inlineText:String{"\(entry.next?.hebrewTitle ?? "זמנים") \(nextTime)"};private var nextTime:String{guard let d=entry.next?.date else{return"--:--"};return time(d)};private func time(_ d:Date)->String{let f=DateFormatter();f.timeZone=entry.snapshot?.timeZone ?? .current;f.dateFormat="HH:mm";return f.string(from:d)};private var progress:Double{guard let s=entry.snapshot?.items.first(where:{$0.key=="sunrise"})?.date,let e=entry.snapshot?.items.first(where:{$0.key=="sunset"})?.date,e>s else{return 0};return min(max(entry.date.timeIntervalSince(s)/e.timeIntervalSince(s),0),1)}}

private struct SolarMini:View{let snapshot:ZmanSnapshot?;let now:Date;var body:some View{GeometryReader{g in ZStack{Path{p in p.move(to:.init(x:g.size.width-8,y:g.size.height-8));p.addQuadCurve(to:.init(x:8,y:g.size.height-8),control:.init(x:g.size.width/2,y:-g.size.height/2))}.stroke(.secondary.opacity(.25),lineWidth:2);Circle().fill(.orange).frame(width:18,height:18).position(x:g.size.width*(1-CGFloat(progress)),y:max(10,g.size.height-8-sin(.pi*progress)*(g.size.height-20)))}};private var progress:Double{guard let s=snapshot?.items.first(where:{$0.key=="sunrise"})?.date,let e=snapshot?.items.first(where:{$0.key=="sunset"})?.date,e>s else{return 0};return min(max(now.timeIntervalSince(s)/e.timeIntervalSince(s),0),1)}}

struct ZmanimLiveActivityWidget:Widget{var body:some WidgetConfiguration{ActivityConfiguration(for:ZmanimActivityAttributes.self){context in HStack{Image(systemName:context.state.icon).foregroundStyle(.orange);VStack(alignment:.leading){Text(context.state.title).bold();Text(timerInterval:Date()...context.state.targetDate,countsDown:true).monospacedDigit()};Spacer();Text(context.attributes.cityName).font(.caption).foregroundStyle(.secondary)}.padding().activityBackgroundTint(.zmanBackground).activitySystemActionForegroundColor(.zmanIndigo)}dynamicIsland:{context in DynamicIsland{DynamicIslandExpandedRegion(.leading){Image(systemName:context.state.icon).foregroundStyle(.orange)};DynamicIslandExpandedRegion(.center){Text(context.state.title).bold()};DynamicIslandExpandedRegion(.trailing){Text(timerInterval:Date()...context.state.targetDate,countsDown:true).monospacedDigit()};DynamicIslandExpandedRegion(.bottom){Text(context.attributes.cityName).font(.caption)}}compactLeading:{Image(systemName:context.state.icon)}compactTrailing:{Text(timerInterval:Date()...context.state.targetDate,countsDown:true).monospacedDigit().frame(width:48)}minimal:{Image(systemName:"sun.max.fill")}}}}

@main struct ZmanimWidgetBundle:WidgetBundle{var body:some Widget{ZmanimWidget();ZmanimLiveActivityWidget()}}
