import UIKit
import UserNotifications
import UserNotificationsUI

final class NotificationViewController:UIViewController,UNNotificationContentExtension {
 private let titleLabel=UILabel(),timeLabel=UILabel(),countdownLabel=UILabel(),horizon=UIView()
 override func viewDidLoad(){super.viewDidLoad();view.backgroundColor=UIColor(red:0.972,green:0.966,blue:0.936,alpha:1);titleLabel.font=.preferredFont(forTextStyle:.title2);titleLabel.textAlignment=.right;timeLabel.font=.monospacedDigitSystemFont(ofSize:34,weight:.semibold);timeLabel.textAlignment=.right;countdownLabel.font=.preferredFont(forTextStyle:.headline);countdownLabel.textColor=.secondaryLabel;countdownLabel.textAlignment=.right;horizon.backgroundColor=UIColor.systemOrange.withAlphaComponent(0.14);horizon.layer.cornerRadius=14;let stack=UIStackView(arrangedSubviews:[horizon,titleLabel,timeLabel,countdownLabel]);stack.axis=.vertical;stack.spacing=8;stack.translatesAutoresizingMaskIntoConstraints=false;view.addSubview(stack);NSLayoutConstraint.activate([stack.leadingAnchor.constraint(equalTo:view.leadingAnchor,constant:20),stack.trailingAnchor.constraint(equalTo:view.trailingAnchor,constant:-20),stack.topAnchor.constraint(equalTo:view.topAnchor,constant:18),stack.bottomAnchor.constraint(lessThanOrEqualTo:view.bottomAnchor,constant:-18),horizon.heightAnchor.constraint(equalToConstant:42)])}
 func didReceive(_ notification:UNNotification){let c=notification.request.content;titleLabel.text=c.userInfo["zmanTitle"] as? String ?? c.title;let target=(c.userInfo["zmanTime"] as? Double).map{Date(timeIntervalSince1970:$0)};if let target{let f=DateFormatter();f.dateFormat="HH:mm";timeLabel.text=f.string(from:target);let mins=max(0,Int(ceil(target.timeIntervalSinceNow/60)));countdownLabel.text=mins>0 ? "נותרו \(mins) דקות":"הזמן הגיע"}else{timeLabel.text="";countdownLabel.text=c.body};let image=UIImageView(image:UIImage(systemName:"sunset.fill"));image.tintColor=.systemOrange;image.translatesAutoresizingMaskIntoConstraints=false;horizon.addSubview(image);NSLayoutConstraint.activate([image.centerXAnchor.constraint(equalTo:horizon.centerXAnchor),image.centerYAnchor.constraint(equalTo:horizon.centerYAnchor),image.widthAnchor.constraint(equalToConstant:24),image.heightAnchor.constraint(equalToConstant:24)])}
}
