import SwiftUI
struct NotificationSettingsView:View {@EnvironmentObject private var model:AppModel;@State private var customName="";@State private var customKey="sunrise";@State private var customOffset = -15
 var body:some View{NavigationStack{ScrollView{VStack(spacing:22){hero;locationCard;specialCard;rulesCard;customCard;saveButton
#if DEBUG
NavigationLink("דיאגנוסטיקה (DEBUG)"){DebugDiagnosticsView()}.font(.headline).foregroundStyle(.secondary).padding(.top,8)
#endif
}.padding(18)}.background(Color.zmanBackground.ignoresSafeArea()).navigationTitle("התראות").navigationBarTitleDisplayMode(.inline)}}
 private var hero:some View{VStack(spacing:12){Text("✦  התראות אישיות  ✦").font(.caption).tracking(3).foregroundStyle(.secondary);Text("ההתראות שלי").font(.system(size:38,weight:.bold));Text("הפעל את ההתראות שתרצה, ובחר כמה דקות מראש לקבל כל אחת.").multilineTextAlignment(.center).foregroundStyle(.secondary);Button{Task{await model.sendTestNotification()}}label:{Label("שלח התראת בדיקה",systemImage:"bell")}.buttonStyle(.bordered)}.padding(.vertical,8)}
 private var locationCard:some View{VStack(alignment:.leading,spacing:14){Label("העיר שלי",systemImage:"location.circle.fill").font(.title2.bold()).foregroundStyle(Color.zmanInk);Picker("מקור מיקום",selection:$model.settings.locationMode){ForEach(LocationMode.allCases){Text($0.title).tag($0)}}.pickerStyle(.segmented);if model.settings.locationMode == .fixed{TextField("חפש עיר או יישוב",text:$model.settings.fixedCity).textFieldStyle(.roundedBorder)}else{Label(model.cityName,systemImage:"location.fill").foregroundStyle(.secondary)}}.padding(18).zmanCard()}
 private var specialCard:some View{VStack(spacing:0){settingToggle(title:"התראה על זמני שבת וחג",subtitle:"כניסה ויציאה לפי העיר שלך",icon:"calendar.badge.clock",isOn:$model.settings.shabbatMasterEnabled);Divider();settingToggle(title:"שבת",subtitle:"כניסת שבת, יציאת שבת ורבנו תם",icon:"bell",isOn:$model.settings.shabbatMasterEnabled);Divider();settingToggle(title:"חגים וצומות",subtitle:"כניסה ויציאה של ימים טובים וצומות",icon:"calendar.badge.clock",isOn:$model.settings.holidayMasterEnabled)}.zmanCard()}
 private var rulesCard:some View{VStack(alignment:.leading,spacing:0){HStack{Image(systemName:"clock").foregroundStyle(Color.zmanIndigo);VStack(alignment:.leading){Text("זמני היום").font(.title2.bold());Text("הפעל תזכורת לכל זמן שתבחר.").font(.caption).foregroundStyle(.secondary)}}.padding(18);Divider();ForEach($model.settings.rules){$rule in RuleEditor(rule:$rule);if rule.id != model.settings.rules.last?.id{Divider().padding(.horizontal,16)}}}.zmanCard()}
 private var customCard:some View{VStack(alignment:.leading,spacing:14){Label("תזכורות מותאמות",systemImage:"sparkles").font(.title2.bold());Text("תזכורת עם שם משלך, מעוגנת לזמן שתבחר.").font(.caption).foregroundStyle(.secondary);TextField("שם התזכורת (למשל: להניח תפילין)",text:$customName).textFieldStyle(.roundedBorder);Picker("זמן בסיס",selection:$customKey){ForEach(HebcalService.definitions,id:\.key){Text($0.hebrewTitle).tag($0.key)}};HStack{Stepper(value:$customOffset,in:-120...120,step:5){Text(offsetText(customOffset)).monospacedDigit()};Button{addCustom()}label:{Label("הוסף תזכורת",systemImage:"plus")}.buttonStyle(.bordered)}}.padding(18).zmanCard()}
 private var saveButton:some View{Button{Task{await model.saveSettings()}}label:{Label("שמירת הגדרות",systemImage:"bell.badge").frame(maxWidth:.infinity).padding(.vertical,8)}.buttonStyle(.borderedProminent).tint(.zmanIndigo).controlSize(.large)}
 private func settingToggle(title:String,subtitle:String,icon:String,isOn:Binding<Bool>)->some View{HStack{Image(systemName:icon).foregroundStyle(Color.zmanOrange).frame(width:34);VStack(alignment:.leading){Text(title).font(.headline);Text(subtitle).font(.caption).foregroundStyle(.secondary)};Spacer();Toggle("",isOn:isOn).labelsHidden()}.padding(16)}
 private func addCustom(){let name=customName.trimmingCharacters(in:.whitespacesAndNewlines);guard !name.isEmpty else{return};model.settings.rules.append(.init(id:"custom-\(UUID().uuidString)",zmanKey:customKey,title:name,offsetMinutes:customOffset,isEnabled:true,customName:name));customName=""}
 private func offsetText(_ v:Int)->String{v==0 ? "במדויק" : "\(abs(v)) דק׳ \(v<0 ? "לפני":"אחרי")"}
}

private struct RuleEditor:View{@Binding var rule:NotificationRule;private let presets=[0,-5,-10,-15,-20,-30,-45,-60]
 var body:some View{VStack(alignment:.leading,spacing:12){HStack{Image(systemName:icon).foregroundStyle(.secondary).frame(width:28);Text(rule.title).font(.headline);Spacer();Toggle("",isOn:$rule.isEnabled).labelsHidden()};if rule.isEnabled{HStack{Button{rule.offsetMinutes=max(-120,rule.offsetMinutes-5)}label:{Image(systemName:"minus").frame(width:32,height:32)}.buttonStyle(.bordered);Text(offsetText).frame(maxWidth:.infinity).font(.headline.monospacedDigit());Button{rule.offsetMinutes=min(120,rule.offsetMinutes+5)}label:{Image(systemName:"plus").frame(width:32,height:32)}.buttonStyle(.bordered)};ScrollView(.horizontal,showsIndicators:false){HStack{ForEach(presets,id:\.self){value in Button(value==0 ? "במדויק":"\(abs(value))׳ לפני"){rule.offsetMinutes=value}.buttonStyle(.bordered).tint(rule.offsetMinutes==value ? .zmanIndigo:.secondary)}}}}}.padding(16)}
 private var icon:String{rule.zmanKey.contains("tzeit") ? "moon":"clock"};private var offsetText:String{rule.offsetMinutes==0 ? "במדויק":"\(abs(rule.offsetMinutes)) דק׳ \(rule.offsetMinutes<0 ? "לפני":"אחרי")"}}
