import CoreLocation
import Foundation

enum HebcalService {
 static let definitions:[ZmanDefinition]=[
 .init(key:"alotHaShachar",hebrewTitle:"עלות השחר",englishTitle:"Alot HaShachar",icon:"moon.stars.fill"),.init(key:"misheyakir",hebrewTitle:"משיכיר",englishTitle:"Misheyakir",icon:"eye.fill"),.init(key:"sunrise",hebrewTitle:"הנץ החמה",englishTitle:"Sunrise",icon:"sunrise.fill"),.init(key:"sofZmanShmaMGA",hebrewTitle:"סוף זמן ק״ש מג״א",englishTitle:"Latest Shema · MGA",icon:"book.closed.fill"),.init(key:"sofZmanShma",hebrewTitle:"סוף זמן ק״ש גר״א",englishTitle:"Latest Shema · Gra",icon:"book.closed.fill"),.init(key:"sofZmanTfilla",hebrewTitle:"סוף זמן תפילה",englishTitle:"Latest Shacharit",icon:"clock.fill"),.init(key:"chatzot",hebrewTitle:"חצות היום",englishTitle:"Chatzot",icon:"sun.max.fill"),.init(key:"minchaGedola",hebrewTitle:"מנחה גדולה",englishTitle:"Mincha Gedola",icon:"sun.haze.fill"),.init(key:"minchaKetana",hebrewTitle:"מנחה קטנה",englishTitle:"Mincha Ketana",icon:"sun.haze.fill"),.init(key:"plagHaMincha",hebrewTitle:"פלג המנחה",englishTitle:"Plag HaMincha",icon:"sunset.fill"),.init(key:"sunset",hebrewTitle:"שקיעה",englishTitle:"Sunset",icon:"sunset.fill"),.init(key:"tzeit7083deg",hebrewTitle:"צאת הכוכבים",englishTitle:"Tzeit 7.083°",icon:"moon.fill"),.init(key:"candleLighting",hebrewTitle:"כניסת שבת",englishTitle:"Candle Lighting",icon:"flame.fill")]
 struct Response:Decodable{let date:String;let times:[String:String]}
 enum ServiceError:LocalizedError{case invalidURL,invalidResponse(Int);var errorDescription:String?{switch self{case .invalidURL:return"לא ניתן ליצור בקשה ל-Hebcal.";case .invalidResponse(let s):return"Hebcal החזיר שגיאה \(s)."}}}
 static func fetchDays(location:CLLocation,timeZone:TimeZone,starting startDate:Date=Date(),count:Int=8) async throws->[ZmanItem]{var all:[ZmanItem]=[];var cal=Calendar(identifier:.gregorian);cal.timeZone=timeZone;for offset in 0..<count{guard let day=cal.date(byAdding:.day,value:offset,to:startDate) else{continue};all += try await fetchDay(location:location,timeZone:timeZone,date:day)};return all.sorted{$0.date<$1.date}}
 static func fetchDay(location:CLLocation,timeZone:TimeZone,date:Date) async throws->[ZmanItem]{var c=URLComponents(string:"https://www.hebcal.com/zmanim");c?.queryItems=[.init(name:"cfg",value:"json"),.init(name:"latitude",value:String(format:"%.6f",location.coordinate.latitude)),.init(name:"longitude",value:String(format:"%.6f",location.coordinate.longitude)),.init(name:"tzid",value:timeZone.identifier),.init(name:"date",value:apiDate(date,timeZone:timeZone)),.init(name:"sec",value:"1")];guard let url=c?.url else{throw ServiceError.invalidURL};let(data,response)=try await URLSession.shared.data(from:url);guard let http=response as? HTTPURLResponse,200...299 ~= http.statusCode else{throw ServiceError.invalidResponse((response as? HTTPURLResponse)?.statusCode ?? -1)};let decoded=try JSONDecoder().decode(Response.self,from:data);let parser=ISO8601DateFormatter();var items:[ZmanItem]=definitions.compactMap{d in guard let raw=decoded.times[d.key],let date=parser.date(from:raw) else{return nil};return ZmanItem(key:d.key,hebrewTitle:d.hebrewTitle,englishTitle:d.englishTitle,icon:d.icon,date:date)};if let sunset=items.first(where:{$0.key=="sunset"})?.date {items.append(ZmanItem(key:"tzeitRT",hebrewTitle:"צאת הכוכבים (רבנו תם)",englishTitle:"Rabbeinu Tam · 72 min",icon:"moon.stars.fill",date:sunset.addingTimeInterval(4320)))};return items.sorted{$0.date<$1.date}}
 private static func apiDate(_ date:Date,timeZone:TimeZone)->String{let f=DateFormatter();f.calendar=Calendar(identifier:.gregorian);f.locale=Locale(identifier:"en_US_POSIX");f.timeZone=timeZone;f.dateFormat="yyyy-MM-dd";return f.string(from:date)}
}
